Repository thoth-station/search, pull requests merged in 2022-01, with the labels that each got.

#38 Add app.py to create tag releases
  .thoth.yaml
  app.py
Labels: size/XS, approved

#40 updated cache key
  .github/workflows/continuous-integration-workflow.yml
  .github/workflows/deploy-stage-workflow.yml
  .github/workflows/deploy-workflow.yml
Labels: size/XS, approved

#41 fixed command
  .github/workflows/deploy-stage-workflow.yml
Labels: size/XS, approved

#42 fixed command pt 2
  .github/workflows/deploy-stage-workflow.yml
Labels: size/XS, approved

#43 fixed repo url
  .github/workflows/deploy-stage-workflow.yml
Labels: size/XS, approved

#44 use action
  .github/workflows/deploy-stage-workflow.yml
Labels: size/S, approved

#45 made env var
  .github/workflows/continuous-integration-workflow.yml
  .github/workflows/deploy-stage-workflow.yml
  .github/workflows/deploy-workflow.yml
  README.md
  package.json
  src/config/index.js
  src/routes/RouterConfig.js
Labels: size/S, approved

#46 Fix paganation
  README.md
  src/config/index.js
  src/features/home/api/getPackageExists.js
  src/features/home/api/index.js
  src/features/home/components/PackageSearch.js
  src/features/package/api/getPackageEnvironments.js
  src/features/package/api/getPackageVersions.js
  src/features/package/hooks/useAllEnvironments.js
  src/features/package/routes/PackageOverview.js
Labels: size/L, approved

#50 Dependency metric
  src/components/Layout/NavigationLayout.js
  src/features/advise/hooks/useGraph.js
  src/features/package/components/PackageDependencies/PackageDependencies.js
  src/features/package/components/PackageDependencies/VersionDropdown.js
  src/features/package/components/PackageHeader/PackageHeader.js
  src/features/package/components/ParamDropdown/ParamDropdown.js
  src/features/package/hooks/useSimpleGraph.js
  src/features/package/routes/PackageOverview.js
Labels: size/L, approved

#55 added tests to package overview page
  .eslintrc.json
  package.json
  src/App.js
  src/features/package/components/PackageDependencies/PackageDependencies.js
  src/features/package/components/PackageDependencies/__test__/PackageDependencies.test.js
  src/features/package/components/PackageHeader/PackageHeader.js
  src/features/package/components/PackageHeader/__test__/PackageHeader.test.js
  src/features/package/hooks/index.js
  src/features/package/routes/PackageOverview.js
  src/features/package/routes/__test__/PackageOverview.test.js
  src/providers/app.js
  src/tests/test-utils.js
  yarn.lock
Labels: size/XXL, approved
